# Generated by Django 5.2.6 on 2025-11-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_birthday'),
        ('accounts', '0002_userotp'),
    ]

    operations = [
    ]
