# Generated by Django 5.2.6 on 2025-11-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_customuser_birthday_0002_userotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userotp',
            new_name='accounts_us_user_id_28d874_idx',
            old_name='accounts_us_user_id_idx',
        ),
    ]
